package pt4.iss.nus.cloudapp.model;

import java.io.Serializable;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Picture")
public class Picture implements Serializable {

	private static final long serialVersionUID = 8331074361667921244L;
	private String id;
	private long createdTime;
	private String userId;
	private int likes;
	private String tags;
	private String picUrl;

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "createdTime")
	public long getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(long ct) {
		this.createdTime = ct;
	}

	@DynamoDBAttribute(attributeName = "userId")
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@DynamoDBAttribute(attributeName = "likes")
	public int getLikes() {
		return likes;
	}

	public void setLikes(int likes) {
		this.likes= likes;
	}

	@DynamoDBAttribute(attributeName = "tags")
	public String getTags() {
		return tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@DynamoDBAttribute(attributeName = "picUrl")
	public String getPicUrl() {
		return picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}
}
